### ISSUE TITLE
SQLI Vulnerabilities in Insert() and Update()

### ISSUE THREAD

**Issue by adrian-enspired** [blackdante101/QuerifyPHP#1]
These methods provide an SQL Injection vector. They should use prepared statements and pass data via parameters.

A similar problem exists with `$tblname` - all uses interpolate this arg directly into the query. This is less likely to be user input, but is still an SQLI vector. Table names should be whitelisted (verified against a list of valid table names) - perhaps by providing table names on construct.

**Comment by blackdante101** [comment]
Vulnerabilities have been resolved. 
Thanks :)

**Comment by adrian-enspired** [comment]
No problem  : )

I see `Insert()` was addressed with #2 but note similar problems still exist in `Update()`.
